### ISSUE TITLE
Python code needs to be updated

### ISSUE THREAD

**Issue by twolinin** [vibansal/IntegratedPhasing#2]
Hi,

My python Python version is 3.6.8 and I found that the code in many places seems to need updating, for example, the usage of print and xrange.

> TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?

> File "/*/mstkruskal.py", line 47, in KruskalMST
>     for node in xrange(self.V): parent.append(node); rank.append(0);
> NameError: name 'xrange' is not defined

**Comment by vibansal** [comment]
This code works with python v2.7 and won't work with versions > 3.

**Comment by twolinin** [comment]
Thank you. I should read the documents more carefully

Notes:
The code was developed and tested using python2.7. It will be ported to python3 soon.
